Add PubMed to supported syntax formats

diff --git a/bin/an2query b/bin/an2query
--- a/bin/an2query
+++ b/bin/an2query
@@ -40,6 +40,7 @@ Database syntax formats and ID types
 
   ovid_medline      ID types: pmid, doi, pii
   ovid_embase       ID types: an, eu, pmid, doi
+  pubmed            ID types: pmid, pmcid, doi, lid
 
 Examples
 
@@ -176,6 +177,44 @@ case "$syntax" in
 	sed\
 	    -e '1 i (' \
 	    -e "\$ a ).${OVID_FIELD_LIST}."
+	;;
+
+    pubmed )
+	# Fields to search for in PubMed
+	case "$idtype" in
+	    pmid )
+		PUBMED_FIELD=PMID
+		;;
+	    pmcid )
+		PUBMED_FIELD=PMCID
+		;;
+	    doi )
+		PUBMED_FIELD=AID
+		;;
+	    lid )
+		# Location ID
+		PUBMED_FIELD=LID
+		;;
+	    * )
+	        # unknown argument
+		echo "ERROR: Unknown idtype ${idtype}" >&2
+		exit 1
+		;;
+	esac
+	# Steps: 
+	#  * Delete empty lines or lines containig only whitespace.
+	#  * Add '"' to beginning of each line of the input.
+	#  * Add '"' to end of each line of the input.
+	#    Whitespace at beginning or end of line will be deleted.
+	#  * Add ' OR ' to end of each line except the last one.
+	#  * Add "(" to beginning of file
+	#  * Add ")" and field specification to end of file
+	sed\
+	    -e '/^\s*$/d' - | \
+	sed\
+	    -e 's/^\s*/"/' \
+	    -e "s/\s*$/\"\[${PUBMED_FIELD}\]/" \
+	    -e '$! s/$/ OR /'
 	;;
 
     * )	
