Add query generation for Citavi

diff --git a/bin/an2query b/bin/an2query
--- a/bin/an2query
+++ b/bin/an2query
@@ -42,6 +42,7 @@ Database syntax formats and ID types
   ovid_medline      ID types: pmid, pmcid, doi, pii
   ovid_embase       ID types: an, eu, pmid, doi
   cochrane_library  ID types: an, doi, tn, none
+  citavi            ID types: doi, pmcid, pmid
 
 Examples
 
@@ -256,6 +257,41 @@ case "$syntax" in
 	    -e '$! s/$/ OR /' | \
 	tr "\n" " "
 	;;
+
+    citavi )
+    	# Fields to search for in Citavi citation manager
+	case "$idtype" in
+	    doi )
+		CITAVI_FIELD_SPEC="DOI"
+		;;
+	    pmcid )
+		CITAVI_FIELD_SPEC="PMCID"
+		;;
+	    pmid )
+		CITAVI_FIELD_SPEC="PubMedId"
+		;;
+	    * )
+		# unknown argument
+		echo "ERROR: Unknown idtype ${idtype}" >&2
+		exit 1
+		;;
+	esac
+	# Steps: 
+	#  * Delete empty lines or lines containig only whitespace.
+	#  * Add '(' and field specification to beginning of each line of the input.
+	#  * Add ')' to end of each line of the input.
+	#    Whitespace at beginning or end of line will be deleted.
+	#  * Add ' OR ' to end of each line except the last one.
+	#  * Join lines
+	sed\
+	    -e '/^\s*$/d' - | \
+	sed\
+    	    -e "s/^\s*/(${CITAVI_FIELD_SPEC}: /" \
+	    -e 's/\s*$/)/' \
+	    -e '$! s/$/ OR /' | \
+	tr "\n" " "
+	;;
+
     * )	
 	echo "ERROR: Unknown database syntax ${syntax}" >&2
 	exit 1
