Add PMC syntax

diff --git a/bin/an2query b/bin/an2query
--- a/bin/an2query
+++ b/bin/an2query
@@ -39,6 +39,7 @@ Database syntax formats and ID types
   Known syntax formats are host and database specific:
 
   pubmed              ID types: pmid, pmcid, doi, lid
+  pmc                 ID types: pmid, pmcid, doi
   ovid_medline        ID types: pmid, pmcid, doi, pii
   ovid_embase         ID types: an, eu, pmid, doi
   cochrane_library    ID types: an, doi, tn, none
@@ -137,6 +138,39 @@ case "$syntax" in
 	sed\
 	    -e 's/^\s*/"/' \
 	    -e "s/\s*$/\"\[${PUBMED_FIELD}\]/" \
+	    -e '$! s/$/ OR /'
+	;;
+
+    pmc )
+	# Fields to search for in PubMed Central
+	case "$idtype" in
+	    pmid )
+		PMC_FIELD=PMID
+		;;
+	    pmcid )
+		# Apparently, there is no dedicated field for PMCIDs that can be searched.
+		PMC_FIELD=ALL
+		;;
+	    doi )
+		PMC_FIELD=AID
+		;;
+	    * )
+	        # unknown argument
+		echo "ERROR: Unknown idtype ${idtype}" >&2
+		exit 1
+		;;
+	esac
+	# Steps: 
+	#  * Delete empty lines or lines containig only whitespace.
+	#  * Add '"' to beginning of each line of the input.
+	#  * Add '"' and field specification to end of each line of the input.
+	#    Whitespace at beginning or end of line will be deleted.
+	#  * Add ' OR ' to end of each line except the last one.
+	sed\
+	    -e '/^\s*$/d' - | \
+	sed\
+	    -e 's/^\s*/"/' \
+	    -e "s/\s*$/\"\[${PMC_FIELD}\]/" \
 	    -e '$! s/$/ OR /'
 	;;
 
