Fix case when empty line at end of input file
Empty lines at the end of file are deleted. This messes up addressing
the end of file in the same sed call. Therfore, split to successive sed
calls.

diff --git a/bin/pmid2ovid_medline b/bin/pmid2ovid_medline
--- a/bin/pmid2ovid_medline
+++ b/bin/pmid2ovid_medline
@@ -1,4 +1,4 @@
-﻿#!/bin/sh
+﻿#!/bin/env sh
 # Convert a list of PubMed-IDs (PMIDs) to a search string for Ovid MEDLINE
 # 
 # Either the name of a file containing the PMIDs can be given as an argument 
@@ -20,28 +20,31 @@ OVID_FIELD_LIST=ui
 
 if test -n "$1" ; then
     PMID_FILE=$1
-    if ! test -r "$PMID_FILE" ; then
-	>&2 echo "Cannot read from file \"${PMID_FILE}\". Abort!"
-	exit 1
-    fi
 else
     PMID_FILE=-
 fi
 
+if ! test -r "$PMID_FILE" ; then
+    >&2 echo "Cannot read from file \"${PMID_FILE}\". Abort!"
+    exit 1
+fi
+
 # Steps: 
-#  * Add "(" to beginning of file
 #  * Delete empty lines or lines containig only whitespace.
 #  * Add '"' to beginning of each line of the input.
 #  * Add '"' to end of each line of the input.
 #    Whitespace at beginning or end of line will be deleted.
 #  * Add ' OR ' to end of each line except the last one.
+#  * Add "(" to beginning of file
 #  * Add ")" and field specification to end of file
+cat "${PMID_FILE}" | \
 sed\
-  -e '1 i ('\
-  -e '/^\s*$/d'\
-  -e 's/^\s*/"/'\
-  -e 's/\s*$/"/'\
-  -e '$! s/$/ OR /'\
-  -e "\$ a ).${OVID_FIELD_LIST}."\
-  $PMID_FILE
+  -e '/^\s*$/d' | \
+sed\
+  -e 's/^\s*/"/' \
+  -e 's/\s*$/"/' \
+  -e '$! s/$/ OR /' | \
+sed\
+  -e '1 i (' \
+  -e "\$ a ).${OVID_FIELD_LIST}."
 
